
apiVersion: v1
kind: Service

metadata:
  name: task-manager-service
  labels: 
    app: task-manager

#spec: Service Configuration
spec:
  type: NodePort
  selector: 
    app: task-manager
  ports:
  - protocol: TCP
    targetPort: 5000
    port: 5000
    nodePort: 30080

